### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Embi2741995** [Omega-Slender/INTENSE-RP-API#5]
I've installed the Silly Tavern through the git (version 1.10.4) and followed your tutorial to the last bit. Everything looks good, it says the API is valid, but when I actually try to type a message, the  Intense RP console shows this and doesn't actually generate anything. What did I do wrong? :/

![dsadassd](https://github.com/Omega-Slender/INTENSE-RP-API/assets/146766536/fffe7320-104f-412b-bb1a-24054e92f898)

**Comment by MadnessTeapot** [comment]
This is most likely due to another POE update, the API is working as the connection is happening, the problem is in sending the message.
![image](https://github.com/Omega-Slender/INTENSE-RP-API/assets/38735247/43135478-c4a0-4f92-9541-204616e314bb)
![image](https://github.com/Omega-Slender/INTENSE-RP-API/assets/38735247/fd9d36a8-0266-4a88-a47b-c020de884013)

**Comment by Omega-Slender** [comment]
I have already updated the API, I hope it works for you.
